version: '3'
services:
    frontend:
        build:
            context: ./
            dockerfile: Dockerfile
        container_name: frontend
        networks:
            - app-network
        ports:
            - "3000:3000"
        restart: unless-stopped
        volumes:
            - ./:/app
            - /app/node_modules
            - /app/.next
     
networks:
  app-network:
    driver: bridge

